### ISSUE TITLE
NullPointerException when trying to index a string

### ISSUE THREAD

**Issue by hlassiege** [jianfengye/elasticsearch-synonym-remote#1]
Hi,

We tried to use this plugin but without any success so far.

Each time we try to index something, we have this stacktrace in ES logs : 

```
[2017-02-04 21:04:58,554][DEBUG][action.index             ] [Ebenezer Laughton] [test][0], node[NxiK-wlUTtO6UM0E743eoQ], [P], s[STARTED]: Failed to execute [index {[test][test][AVoKuswbL1NQTcvSllro], source[{
"fullname" : "j2ee"
}
]}]
java.lang.NullPointerException
	at org.elasticsearch.index.synonym.FileRemoteSynonymTokenFilterFactory.create(FileRemoteSynonymTokenFilterFactory.java:118)
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:86)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:113)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:113)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:182)
	at org.apache.lucene.document.Field.tokenStream(Field.java:554)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:611)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1252)
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:345)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:287)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:259)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:482)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:206)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-04 21:05:04,733][INFO ][synonym-remote           ] remote_synonyms_path https://dev.hopwork.com:8443/search/admin/index/synonyms/tech/fr error!
java.lang.NullPointerException
	at org.elasticsearch.index.synonym.FileRemoteSynonymTokenFilterFactory$FileRemoteMonitor.run(FileRemoteSynonymTokenFilterFactory.java:144)
	at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:508)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

To reproduce, this is our index settings : 
```
{
    "number_of_replicas" : 0,
    "analysis": {
        "analyzer": {
            "fr":{
                "type":"custom",
                "tokenizer":"whitespace",
                "filter":["lowercase", "asciifolding", "elision", "synonym_tech_fr"]
            }
        },
        "filter":{
            "synonym_tech_fr" : {
                "type" : "file_remote_synonym",
                "remote_synonyms_path" : "https://localhost/synonyms.txt"
            }
        }
    }
}
```

Our mappings :
```
{
    "test": {
        "_source": {
            "enabled": true
        },
        "_timestamp": {
            "enabled": true,
            "store": true
        },
        "properties": {
            "fullname": {
                "type": "string",
                "analyzer": "fr"
            }
        }
    }
}
```

The data we try to index : 
```
{
"fullname" : "j2ee"
}
```

The synonym file : 
```
développement java, développeur java, j2e, j2ee, j2se, java ee, java j2e, java/j2ee, java/jee, javaee, jee => java

```

**Comment by hlassiege** [comment]
Sometimes, the indexing works with the previous data. But a call to the analyze endpoint fails with an NPE :

http://localhost:9200/test/_analyze?text=j2se&analyzer=fr
